name: Deploy QA to Heroku (DEV Server)

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node (20.11.0)
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Login to Heroku
        uses: heroku/actions/login@v2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        uses: heroku/actions/deploy-via-git@v2
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
